// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-SH2Xc2DHB61wWqqL_g0WQR_m_Fk7-nQ',
    appId: '1:889780000169:web:cf914a161ff180d6d0a0b8',
    messagingSenderId: '889780000169',
    projectId: 'attendancemanager-459cb',
    authDomain: 'attendancemanager-459cb.firebaseapp.com',
    storageBucket: 'attendancemanager-459cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4oyRJc1idUiSjvMxbAfQXbZibBE5fRX0',
    appId: '1:889780000169:android:6d96560bf5a3a502d0a0b8',
    messagingSenderId: '889780000169',
    projectId: 'attendancemanager-459cb',
    storageBucket: 'attendancemanager-459cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNOOIs_QwGP37wFFPpK6FS42XFFp2krM4',
    appId: '1:889780000169:ios:b3dd612cc4670314d0a0b8',
    messagingSenderId: '889780000169',
    projectId: 'attendancemanager-459cb',
    storageBucket: 'attendancemanager-459cb.appspot.com',
    iosBundleId: 'com.example.attendanceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNOOIs_QwGP37wFFPpK6FS42XFFp2krM4',
    appId: '1:889780000169:ios:b3dd612cc4670314d0a0b8',
    messagingSenderId: '889780000169',
    projectId: 'attendancemanager-459cb',
    storageBucket: 'attendancemanager-459cb.appspot.com',
    iosBundleId: 'com.example.attendanceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-SH2Xc2DHB61wWqqL_g0WQR_m_Fk7-nQ',
    appId: '1:889780000169:web:87c75374fc70d343d0a0b8',
    messagingSenderId: '889780000169',
    projectId: 'attendancemanager-459cb',
    authDomain: 'attendancemanager-459cb.firebaseapp.com',
    storageBucket: 'attendancemanager-459cb.appspot.com',
  );

}